-- Post-update "What's New" bullet lists, keyed by version string.
-- Add an entry for each release with noteworthy changes.
-- Omit a version to show no changelog on that update.
--
-- Example:
-- ["0.1.0"] = {
--     "New feature added",
--     "Bug fix for ...",
-- },

return {
    ["1.0.2"] = {
        "Automatically disable incompatible plugins",
        "Access reader menu from page browser",
        'Add "Report a Bug" button in Zen Settings > About',
        "Add in-app changelogs",
        "Add new quick settings buttons, hide when plugin not installed",
        "Add Bulgarian translation",
        "Bug fixes and performance improvements",
    },
    ["1.0.3"] = {
        "Fix: some quick settings buttons not showing",
        "Fix: language defaulting to english after plugin restart",
        "Bug fixes and performance improvements",
    },
    ["1.1.0"] = {
        "Add scroll bar with page numbers, jump to page, and buttons + skip (Library > Scroll bar)",
        "Add title/author strip (Library > Covers)",
        "Add padding to covers in list views",
        "Add Calibre search in navbar, label is Search (Navbar > Tabs)",
        "Add custom buttons (Quick settings > Buttons)",
        "Add LocalSend, Screenshot, Chess, Battery Stats to Quick Settings",
        "Add book information to context menu (Tap + hold book > Details)",
        "Collections and history have independent displays (Tap + hold Navbar)",
        "Support additional home folders (Library > Home folder)",
        "Support for non touchscreen devices",
        "Bug fixes and performance improvements",
    },
    ["1.2.0"] = {
        "Add Tags to Navbar (Settings > Navbar)",
        "Add custom tabs to Navbar (Settings > Navbar)",
        "Add filtering for all views",
        "Add dim finished books (Library > Covers)",
        "Add/remove from collections via context menu",
        "Add a toggle for folder stack spines (Library > Folders)",
        "Allow remove from history in context menu",
        "Better support for multiple home folders",
        "Up folder fixes and styling",
        "Fixed lag in folder/path chooser",
        "Fixed reader menu not opening on some devices",
        "Bug fixes and performance improvements",
    },
    ["1.2.1"] = {
        "Update flow enhancements (abort/prompt for network)",
        "Show a notification dot on Zen Settings icon when an update is available",
        "Adjust Zen cover image for screensaver",
        "Fix search (revert whole word searching)",
        "Fix Navbar tabs not showing after updating settings",
        "Fix unread status not fully resetting status",
        "Fix hide list borders not applying immediately",
        "Fix mosaic covers not showing in TBR",
        "Fix a rare issue where duplicate items could show in status bar/navbar",
        "Bug fixes and performance improvements",
    },
    ["1.3.0"] = {
        "Updated customization options for reader status bars (Reader > Top/Bottom Status bar)",
        "Add support for custom folder covers with image files",
        "Add support for more custom icons in Quick settings & Navbar",
        "Add support for setting font and font size in library",
        "Add color options for badges",
        "Updated placeholders for folders/books",
        "Add better support for legacy/non-touch devices",
        "Add refresh cached book info to edit menu",
        "Add toggle for whole word search matching (Global > Search)",
        "Add stack option for folder covers (Library > Folders > Covers)",
        "Add 2:3 and 3:4 cover ration in uniform covers (Library > Folders > Covers)",
        "Fix bug in lockdown mode allowing context menu when disabled via settings",
        "Fix KOReader behavior/bug - set status to reading on opening book",
        "Fix bug in search results always showing mosaic view",
        "Fixed bugs in OPDS & respect new 3:4 cover ratio",
        "Add Czech translation",
        "Bug fixes and performance improvements",
    },
    ["1.4.0"] = {
        "Refresh visuals for update checking",
        "Enhance Zen UI update security + method",
        "Add option to disable automatic update checking (About > Updates)",
        "Add changelog for previous versions",
        "Add book title, author, chapter to top reader status bar",
        "Add Japanese translation",
        "Add Vietnamese translation",
        "Update quick lookup for next KOReader release",
        "Fix rare crash on background update check",
        "Bug fixes and performance improvements",
    },
}
