local defaults = {
    _meta = {
        schema_version = 1,
        files_per_page_defaulted = false,
        menu_activation_defaulted = false,
        screensaver_backup_created = false,
        footer_backup_created = false,
        quickstart_shown_for_version = false,
        sort_defaults_applied = false,
    },
    localization = {
        default_locale = "en",
        locales = {
            "en",
            "it",
            "es",
            "fr",
            "nl",
            "pt_BR",
            "pt_PT",
            "ro",
            "ru",
            "zh_CN",
            "zh_TW",
        },
    },
    features = {
        navbar = true,
        quick_settings = true,
        zen_mode = true,
        status_bar = true,
        disable_top_menu_swipe_zones = true,
        browser_folder_cover = true,
        browser_hide_underline = true,
        browser_hide_up_folder = true,
        favorites = true,
        collections = true,
        history = true,
        search = true,
        browser_cover_rounded_corners = true,
        browser_cover_mosaic_uniform = true,
        partial_page_repaint = false,
        reader_top_status_bar = true,
        reader_bottom_menu = false,
        night_mode_schedule = false,
        warmth_schedule     = false,
        brightness_schedule = false,
        page_browser        = true,
        restore_library_view = false,
        highlight_lookup     = true,
        dict_quick_lookup    = true,
        custom_icons_enabled = false,
        lockdown_mode        = false,
        zen_opds             = true,
    },
    navbar = {
        show_tabs = {
            books = true,
            manga = false,
            news = false,
            continue = true,
            history = false,
            favorites = true,
            collections = false,
            authors = true,
            series = true,
            stats = false,
            exit = false,
            page_left = false,
            page_right = false,
            menu = false,
        },
        tab_order = { "page_left", "books", "manga", "news", "authors", "series", "continue", "favorites", "history", "collections", "stats", "exit", "page_right", "menu" },
        show_labels = true,
        books_label = "Library",
        manga_action = "rakuyomi",
        manga_folder = "",
        news_action = "quickrss",
        news_folder = "",
        colored = false,
        active_tab_color = { 0x33, 0x99, 0xFF },
        active_tab_styling = true,
        active_tab_bold = false,
        active_tab_underline = true,
        underline_above = false,
        show_top_border = true,
    },
    quick_settings = {
        button_order = { "wifi", "night", "rotate", "zen", "lockdown", "usb", "search", "quickrss", "cloud", "zlibrary", "calibre", "notion", "streak", "opds", "filebrowser", "restart", "exit", "sleep" },
        show_buttons = {
            wifi = true,
            night = true,
            rotate = true,
            zen = true,
            lockdown = false,
            usb = false,
            search = false,
            quickrss = false,
            cloud = false,
            zlibrary = false,
            calibre = false,
            restart = true,
            exit = false,
            sleep = true,
            notion = false,
            streak = false,
            opds = false,
            filebrowser = false,
        },
        show_frontlight = true,
        show_warmth = true,
    },
    status_bar = {
        custom_text = " ",
        separator_key = "small-space",
        custom_separator = "  ",
        left_order   = { "time" },
        center_order = {},
        right_order  = { "wifi", "battery" },
        time_12h = true,
        show_bottom_border = false,
        colored = false,
        bold_text = false,
        hide_browser_bar = true,
    },
    browser_hide_up_folder = {
        hide_up_folder = true,
    },
    additional_home_dirs = {},
    browser_list_item_layout = {
        hide_list_borders = false,
    },
    browser_cover_badges = {
        show_mosaic_progress = true,
        show_native_progress_bar = false,
        show_new_banner = true,
        badge_size = "compact",
        dim_finished_books = false,
    },
    browser_page_count = {
        show_page_count = false,
    },
    browser_series_badge = {
        show_series_badge = false,
    },
    mosaic_title_strip = {
        show_title  = false,
        show_author = false,
    },
    zen_scroll_bar = {
        style              = "dots",     -- "bar" | "dots" | "page_number"
        page_number_format = "total",  -- "current" | "total"
        hold_skip          = "ends",       -- "10" | "20" | "ends"
    },
    context_menu = {
        allow_delete = false,
    },
    reader_top_status_bar = {
        font_face = "default",
        font_size = 14,
        left_order       = {},
        center_order     = { "time" },
        right_order      = {},
        separator_key    = "small-space",
        custom_separator = "  ",
        custom_text      = "",
    },
    reader_footer = {
        verbose_chapter_time = false,
        hide_in_cbz = false,
        backup_preset = nil,
    },
    highlight_lookup = {
        allow_unknown_items = false,
        show_wikipedia      = false,
    },
    dict_quick_lookup = {},

    night_mode_schedule = {
        night_on_h  = 20,
        night_on_m  = 0,
        night_off_h = 7,
        night_off_m = 0,
    },
    warmth_schedule = {
        day_h       = 7,
        day_m       = 0,
        day_value   = 3,
        night_h     = 20,
        night_m     = 0,
        night_value = 8,
    },
    brightness_schedule = {
        day_h       = 7,
        day_m       = 0,
        day_value   = 20,
        night_h     = 20,
        night_m     = 0,
        night_value = 5,
    },
    sleep_screen = {
        presets = {},           -- { { name=…, screensaver_type=…, … }, … }
        active_preset = nil,   -- name of currently active preset, or nil
    },
    stats_page = {
        rows = { "today", "this_month", "this_year", "all_time", "library" },
    },
    lockdown = {
        disable_context_menu      = false,
        disable_bottom_menu_swipe = false,
        disable_word_selection    = false,
        disable_hold_search       = false,
        require_hold_in_qs        = false,
        disable_settings_panel    = false,
        magnify_ui                = false,
    },
}

return defaults
